import type { Metadata } from "next";
import { LoadingProvider } from "@/context/LoadingContext";
import "./globals.css";
import TransitionProvider from "@/context/TransitionContext";
import Nav from "@/components/Nav";
import { Cursor } from "@/components/Cursor";
import { Inter, Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("cursor-none", "font-sans", geist.variable)}>
      <body>
        <LoadingProvider>
          <TransitionProvider>
            {/* <Menu></Menu> */}
            <div className=" absolute w-screen flex items-center justify-center h-32 magnet">
              <Nav></Nav>
            </div>

            <div>
              <Cursor></Cursor>
              {children}
            </div>
          </TransitionProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
